"""
Image Generation Service using Stability AI
Handles image generation, caching, and error management
"""

import os
import base64
import requests
import hashlib
import json
from typing import Dict, Optional
from pathlib import Path

class ImageGenerationService:
    def __init__(self):
        self.api_key = os.getenv('STABILITY_API_KEY')
        if not self.api_key:
            print("WARNING: STABILITY_API_KEY not set in environment")
        
        self.cache_dir = Path('image_cache')
        self.cache_dir.mkdir(exist_ok=True)
        
        self.api_url = "https://api.stability.ai/v1/generation/stable-diffusion-xl-1024-v1-0/text-to-image"
    
    def generate_image(self, prompt: str, style: str = "digital-art") -> Dict:
        """
        Generate image from text prompt
        
        Args:
            prompt: Text description of the image
            style: Style preset (digital-art, photographic, 3d-model, etc.)
        
        Returns:
            {
                'image_base64': str,
                'cached': bool,
                'cost': float,
                'success': bool,
                'error': str (if failed)
            }
        """
        try:
            # Check cache first
            cache_key = self._get_cache_key(prompt, style)
            cached_image = self._get_from_cache(cache_key)
            
            if cached_image:
                print(f"✅ Image found in cache for prompt: {prompt[:50]}...")
                return {
                    'image_base64': cached_image,
                    'cached': True,
                    'cost': 0.0,
                    'success': True
                }
            
            # Generate new image
            print(f"🎨 Generating new image for prompt: {prompt[:50]}...")
            image_data = self._call_stability_api(prompt, style)
            
            # Cache it
            self._save_to_cache(cache_key, image_data)
            
            return {
                'image_base64': image_data,
                'cached': False,
                'cost': 0.02,  # Approximate cost per image
                'success': True
            }
            
        except Exception as e:
            print(f"❌ Image generation failed: {str(e)}")
            return {
                'image_base64': '',
                'cached': False,
                'cost': 0.0,
                'success': False,
                'error': str(e)
            }
    
    def _call_stability_api(self, prompt: str, style: str) -> str:
        """Call Stability AI API to generate image"""
        if not self.api_key:
            raise Exception("STABILITY_API_KEY not configured")
        
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
            "Accept": "application/json"
        }
        
        # Optimize prompt for card design
        optimized_prompt = self._optimize_prompt(prompt)
        
        payload = {
            "text_prompts": [
                {
                    "text": optimized_prompt,
                    "weight": 1
                },
                {
                    "text": "blurry, low quality, distorted, ugly, bad art",
                    "weight": -1  # Negative prompt
                }
            ],
            "cfg_scale": 7,
            "height": 1216,  # Valid SDXL dimension (portrait card)
            "width": 832,    # Valid SDXL dimension  
            "samples": 1,
            "steps": 30,
            "style_preset": style
        }
        
        response = requests.post(
            self.api_url,
            headers=headers,
            json=payload,
            timeout=30
        )
        
        if response.status_code != 200:
            raise Exception(f"API error {response.status_code}: {response.text}")
        
        data = response.json()
        
        if 'artifacts' not in data or len(data['artifacts']) == 0:
            raise Exception("No image generated by API")
        
        return data['artifacts'][0]['base64']
    
    def _optimize_prompt(self, user_prompt: str) -> str:
        """
        Optimize user prompt for better image generation
        Add keywords for quality and style
        """
        quality_terms = "high quality, detailed, professional, beautiful, artistic"
        
        # Add style hints based on content
        if any(word in user_prompt.lower() for word in ['christmas', 'santa', 'holiday']):
            return f"{user_prompt}, {quality_terms}, festive, warm colors, magical atmosphere"
        elif any(word in user_prompt.lower() for word in ['birthday', 'celebration']):
            return f"{user_prompt}, {quality_terms}, joyful, vibrant colors, celebratory"
        elif any(word in user_prompt.lower() for word in ['wedding', 'invitation']):
            return f"{user_prompt}, {quality_terms}, elegant, romantic, soft colors"
        else:
            return f"{user_prompt}, {quality_terms}"
    
    def _get_cache_key(self, prompt: str, style: str) -> str:
        """Generate cache key from prompt and style"""
        combined = f"{prompt}:{style}"
        return hashlib.md5(combined.encode()).hexdigest()
    
    def _get_from_cache(self, cache_key: str) -> Optional[str]:
        """Retrieve image from cache if it exists"""
        cache_file = self.cache_dir / f"{cache_key}.txt"
        
        if cache_file.exists():
            try:
                return cache_file.read_text(encoding='utf-8')
            except Exception as e:
                print(f"Cache read error: {e}")
                return None
        
        return None
    
    def _save_to_cache(self, cache_key: str, image_data: str):
        """Save image to cache"""
        cache_file = self.cache_dir / f"{cache_key}.txt"
        
        try:
            cache_file.write_text(image_data, encoding='utf-8')
            print(f"💾 Image cached successfully")
        except Exception as e:
            print(f"Cache save error: {e}")


# Singleton instance
_image_service = None

def get_image_service() -> ImageGenerationService:
    """Get or create image service instance"""
    global _image_service
    if _image_service is None:
        _image_service = ImageGenerationService()
    return _image_service
